---
- name: get vlans for {{ fabric }}
  uri:
    url: "{{ maas_base }}/MAAS/api/2.0/fabrics/{{ fabric_id }}/vlans/"
    headers:
      Authorization: "{{ Authorization }}"
    return_content: true
  register: _fabric_vlans
  delegate_to: messy-maas

- name:
  debug:
    var: _fabric_vlans.json

- name: create vlans
  uri:
    url: "{{ maas_base }}/MAAS/api/2.0/fabrics/{{ fabric_id }}/vlans/"
    method: POST
    headers:
      Authorization: "{{ Authorization }}"
    body:
      name: "{{ hostvars['messy-maas'].maas.fabrics[fabric][vlan].name }}"
      vid: "{{ vlan.split('.')[1] }}"
      mtu: "{{ hostvars['messy-maas'].maas.fabrics[fabric][vlan].mtu | default(1500) }}"
    body_format: json
    return_content: true
  with_items: "{{ hostvars['messy-maas'].maas.fabrics[fabric] }}"
  loop_control:
    loop_var: vlan
  when:
    - (vlan.split('.')[1] | int) not in (_fabric_vlans.json | json_query(get_vlan_ids))
  vars:
    get_vlan_ids: "[].vid"
  changed_when: true
  delegate_to: messy-maas

- name: update vlans
  uri:
    url: "{{ maas_base }}{{ _fabric_vlans.json | json_query(get_vlan_resource_uri) }}"
    method: PUT
    headers:
      Authorization: "{{ Authorization }}"
    body:
      vid: "{{ vlan.split('.')[1] }}"
      name: "{{ hostvars['messy-maas'].maas.fabrics[fabric][vlan].name }}"
      mtu: "{{ hostvars['messy-maas'].maas.fabrics[fabric][vlan].mtu | default(1500) }}"
    body_format: json
    return_content: true
  with_items: "{{ hostvars['messy-maas'].maas.fabrics[fabric] }}"
  loop_control:
    loop_var: vlan
  when:
    - hostvars['messy-maas'].maas.fabrics[fabric][vlan].name != (_fabric_vlans.json | json_query(get_vlan_name)) or
      hostvars['messy-maas'].maas.fabrics[fabric][vlan].mtu | default(1500) != (_fabric_vlans.json | json_query(get_vlan_mtu))
  vars:
    get_vlan_resource_uri: "[?vid==`{{ vlan.split('.')[1] }}`].resource_uri | [0]"
    get_vlan_name: "[?vid==`{{ vlan.split('.')[1] }}`].name | [0]"
    get_vlan_mtu: "[?vid==`{{ vlan.split('.')[1] }}`].mtu | [0]"
  changed_when: true
  delegate_to: messy-maas

- name: get subnets
  uri:
    url: "{{ maas_base }}/MAAS/api/2.0/subnets/"
    headers:
      Authorization: "{{ Authorization }}"
    return_content: true
  register: _subnets
  delegate_to: messy-maas

- name: create subnet
  uri:
    url: "{{ maas_base }}/MAAS/api/2.0/subnets/"
    method: POST
    headers:
      Authorization: "{{ Authorization }}"
    body:
      cidr: "{{ hostvars['messy-maas'].maas.fabrics[fabric][vlan].subnet }}"
      vid: "{{ vlan.split('.')[1] | int }}"
    body_format: json
    return_content: true
  with_items: "{{ hostvars['messy-maas'].maas.fabrics[fabric] }}"
  loop_control:
    loop_var: vlan
  when: hostvars['messy-maas'].maas.fabrics[fabric][vlan].subnet not in _subnets.json | json_query(get_subnet_cidrs)
  vars:
    get_subnet_cidrs: "[].cidr"
  changed_when: true
  delegate_to: messy-maas

- name: get ip ranges
  uri:
    url: "{{ maas_base }}/MAAS/api/2.0/ipranges/"
    headers:
      Authorization: "{{ Authorization }}"
    return_content: true
  register: _ip_ranges
  delegate_to: messy-maas

# XXX this should get a better when condition
#     I'm taking it for granted that there's only one range in a subnet.
- name: create ip range
  uri:
    url: "{{ maas_base }}/MAAS/api/2.0/ipranges/"
    method: POST
    headers:
      Authorization: "{{ Authorization }}"
    body:
      type: "{{ hostvars['messy-maas'].maas.fabrics[fabric][vlan].ip_range.type }}"
      start_ip: "{{ hostvars['messy-maas'].maas.fabrics[fabric][vlan].ip_range.start_ip }}"
      end_ip: "{{ hostvars['messy-maas'].maas.fabrics[fabric][vlan].ip_range.end_ip }}"
      #subnet: "{{ hostvars['messy-maas'].maas.fabrics[fabric][vlan].subnet }}"
    body_format: json
    return_content: true
  with_items: "{{ hostvars['messy-maas'].maas.fabrics[fabric] }}"
  loop_control:
    loop_var: vlan
  when:
    - hostvars['messy-maas'].maas.fabrics[fabric][vlan].ip_range is defined
    - hostvars['messy-maas'].maas.fabrics[fabric][vlan].subnet not in (_ip_ranges.json | json_query(get_ip_range_cidrs))
  vars:
    get_ip_range_cidrs: "[].subnet.cidr"
  changed_when: true
  delegate_to: messy-maas

- name: get rackcontrollers
  uri:
    url: "{{ maas_base }}/MAAS/api/2.0/rackcontrollers/"
    headers:
      Authorization: "{{ Authorization }}"
    return_content: true
  register: _rackcontrollers
  delegate_to: messy-maas

- name: provide dhcp on vlans
  uri:
    url: "{{ maas_base }}{{ _fabric_vlans.json | json_query(get_vlan_resource_uri) }}"
    method: PUT
    headers:
      Authorization: "{{ Authorization }}"
    body:
      vid: "{{ vlan.split('.')[1] }}"
      primary_rack: "{{ _rackcontrollers.json | json_query( \"[?hostname=='messy-maas'].system_id | [0]\" ) }}"
      dhcp_on: "{{ hostvars['messy-maas'].maas.fabrics[fabric][vlan].dhcp_on }}"
    body_format: json
    return_content: true
  with_items: "{{ hostvars['messy-maas'].maas.fabrics[fabric] }}"
  loop_control:
    loop_var: vlan
  when:
    - hostvars['messy-maas'].maas.fabrics[fabric][vlan].dhcp_on | default(false)
    - not (_fabric_vlans.json | json_query(get_vlan_dhcp_on))
  vars:
    get_vlan_resource_uri: "[?vid==`{{ vlan.split('.')[1] }}`].resource_uri | [0]"
    get_vlan_dhcp_on: "[?vid==`{{ vlan.split('.')[1] }}`].dhcp_on | [0]"
  changed_when: true
  delegate_to: messy-maas
