---
- name: "create bridges on {{ machine.hostname }}"
  uri:
    url: "{{ maas_base }}/MAAS/api/2.0/nodes/{{ machine.system_id }}/interfaces/?op=create_bridge"
    method: POST
    headers:
      Authorization: "{{ Authorization }}"
    body:
      name: "{{ bridge }}"
      parent: "{{ interface_id[ hostvars[machine.hostname].network.bridges[bridge].interfaces[0] ] }}"
    body_format: json
    return_content: true
  with_items: "{{ hostvars[machine.hostname].network.bridges }}"
  loop_control:
    loop_var: bridge
  when:
    - hostvars[machine.hostname].network.bridges is defined
    - bridge not in (machine_interface_set | map(attribute='name') | list)
  register: _create_bridges
  changed_when: true

- name: "update machine_interface_set for {{ machine.hostname }} with new bridges"
  set_fact:
    machine_interface_set: "{{ machine_interface_set + [item.json] }}"
    interface_id: "{{ interface_id | combine({ item.json.name: item.json.id }) }}"
  with_items: "{{ _create_bridges.results }}"
  loop_control:
    label: "{{ item.bridge }}"
  when:
    - item.json is defined
